version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: chat
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - chatdb:/var/lib/mysql
    networks:
      vpcbr:
        ipv4_address: 172.30.80.2
  app:
    image: chat-app
    restart: always
    volumes:
      - ./:/usr/django-chat
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
      - cache
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: 172.30.80.4
      DATABASE_HOST: 172.30.80.2
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      CHAT_SUPERUSER_EMAIL: ${CHAT_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      PYTHONUNBUFFERED: 1
    networks:
      vpcbr:
        ipv4_address: 172.30.80.3
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      vpcbr:
        ipv4_address: 172.30.80.4
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      vpcbr:
        ipv4_address: 172.30.80.5
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.80.0/16
#          gateway: 172.30.80.1
volumes:
  chatdb: