# Generated by Django 3.0.14 on 2021-05-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='recipient',
        ),
    ]
