# Generated by Django 3.0.14 on 2021-05-20 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_roommodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommodel',
            name='sender',
        ),
        migrations.AddField(
            model_name='roommodel',
            name='members',
            field=models.ManyToManyField(related_name='room_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
