# Generated by Django 3.0.7 on 2020-07-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200714_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=models.TextField(blank=True, default='', null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
