# Generated by Django 3.0.7 on 2020-07-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200714_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files/'),
        ),
    ]
